flowchart LR
    m0["ef81a87bd4aa<br/>a1_initial_schema"]
    m1["b2c4f1a8e390<br/>a_user_add_is_active_updated_at"]
    m0 --> m1
    m2["c3d5f1a8b290<br/>a_user_add_avatar_url"]
    m1 --> m2
    m3["d4e6a2c9f1b7<br/>a_user_add_refresh_tokens"]
    m2 --> m3
    m4["e5a1b2c3d4e5<br/>review_companion"]
    m3 --> m4
    m5["f6b2c3d4e5f6<br/>review_catalog"]
    m4 --> m5
    m6["a7c3d4e5f6a7<br/>review_attempt_taxonomy"]
    m5 --> m6
    m7["6d9fe6080e14<br/>d4_add_mastery_records"]
    m6 --> m7
    m8["83bcb2215849<br/>d6_add_review_session_summaries"]
    m7 --> m8
