"""A1: replace profile_traits with fixed 7-card profile_cards

Revision ID: 20a463a3c92c
Revises: 27ad45310510
Create Date: 2026-09-30 21:44:08.487524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20a463a3c92c'
down_revision: Union[str, Sequence[str], None] = '27ad45310510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('source_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('card_key', sa.String(length=50), nullable=False),
    sa.Column('reading', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'card_key', name='uq_profile_cards_profile_id_card_key')
    )
    op.create_index(op.f('ix_profile_cards_profile_id'), 'profile_cards', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_cards_school_id'), 'profile_cards', ['school_id'], unique=False)
    op.create_table('profile_card_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['profile_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_card_corrections_card_id'), 'profile_card_corrections', ['card_id'], unique=False)
    op.create_index(op.f('ix_profile_card_corrections_school_id'), 'profile_card_corrections', ['school_id'], unique=False)
    # Drop order matters: profile_trait_corrections.trait_id FKs into
    # profile_traits, so the child table must go first (autogenerate got
    # this backwards).
    op.drop_index(op.f('ix_profile_trait_corrections_school_id'), table_name='profile_trait_corrections')
    op.drop_index(op.f('ix_profile_trait_corrections_trait_id'), table_name='profile_trait_corrections')
    op.drop_table('profile_trait_corrections')
    op.drop_index(op.f('ix_profile_traits_profile_id'), table_name='profile_traits')
    op.drop_index(op.f('ix_profile_traits_school_id'), table_name='profile_traits')
    op.drop_table('profile_traits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create order matters: profile_trait_corrections.trait_id FKs into
    # profile_traits, so the parent table must exist first (autogenerate
    # got this backwards).
    op.create_table('profile_traits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trait_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('teaching_tip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=20), server_default=sa.text("'still_forming'::character varying"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], name=op.f('profile_traits_profile_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('profile_traits_school_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], name=op.f('profile_traits_source_conversation_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_traits_pkey'))
    )
    op.create_index(op.f('ix_profile_traits_school_id'), 'profile_traits', ['school_id'], unique=False)
    op.create_index(op.f('ix_profile_traits_profile_id'), 'profile_traits', ['profile_id'], unique=False)
    op.create_table('profile_trait_corrections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trait_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resolution_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('profile_trait_corrections_school_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['profile_traits.id'], name=op.f('profile_trait_corrections_trait_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_trait_corrections_pkey'))
    )
    op.create_index(op.f('ix_profile_trait_corrections_trait_id'), 'profile_trait_corrections', ['trait_id'], unique=False)
    op.create_index(op.f('ix_profile_trait_corrections_school_id'), 'profile_trait_corrections', ['school_id'], unique=False)
    op.drop_index(op.f('ix_profile_card_corrections_school_id'), table_name='profile_card_corrections')
    op.drop_index(op.f('ix_profile_card_corrections_card_id'), table_name='profile_card_corrections')
    op.drop_table('profile_card_corrections')
    op.drop_index(op.f('ix_profile_cards_school_id'), table_name='profile_cards')
    op.drop_index(op.f('ix_profile_cards_profile_id'), table_name='profile_cards')
    op.drop_table('profile_cards')
    # ### end Alembic commands ###
