"""A2: replace conversation ended_at with extraction checkpoint

Revision ID: 27ad45310510
Revises: 3a358f4ca337
Create Date: 2026-09-30 21:28:13.781632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27ad45310510'
down_revision: Union[str, Sequence[str], None] = '3a358f4ca337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_extracted_message_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('conversations', 'ended_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'last_extracted_message_count')
    # ### end Alembic commands ###
