"""A5: add profile_trait_corrections table

Revision ID: 3a358f4ca337
Revises: 6d4c3dbc83c1
Create Date: 2026-09-27 01:05:08.717693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a358f4ca337'
down_revision: Union[str, Sequence[str], None] = '6d4c3dbc83c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_trait_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('trait_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['profile_traits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_trait_corrections_school_id'), 'profile_trait_corrections', ['school_id'], unique=False)
    op.create_index(op.f('ix_profile_trait_corrections_trait_id'), 'profile_trait_corrections', ['trait_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_trait_corrections_trait_id'), table_name='profile_trait_corrections')
    op.drop_index(op.f('ix_profile_trait_corrections_school_id'), table_name='profile_trait_corrections')
    op.drop_table('profile_trait_corrections')
    # ### end Alembic commands ###
