"""D4: add mastery records

Revision ID: 6d9fe6080e14
Revises: a7c3d4e5f6a7
Create Date: 2026-09-23 23:11:53.069496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9fe6080e14'
down_revision: Union[str, Sequence[str], None] = 'a7c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastery_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('concept_ref', sa.String(length=100), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('mastery_band', sa.String(length=20), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('assisted_evidence_count', sa.Integer(), nullable=False),
    sa.Column('dominant_error_type', sa.String(length=100), nullable=True),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mastery_band IN ('needs_support', 'developing', 'secure')", name='ck_mastery_band'),
    sa.CheckConstraint('assisted_evidence_count >= 0 AND assisted_evidence_count <= evidence_count', name='ck_mastery_assisted_count'),
    sa.CheckConstraint('attempt_count >= evidence_count', name='ck_mastery_attempt_count'),
    sa.CheckConstraint('evidence_count >= 1', name='ck_mastery_evidence_count'),
    sa.CheckConstraint('mastery_score >= 0 AND mastery_score <= 1', name='ck_mastery_score'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['review_subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'subject_id', 'concept_ref', name='uq_mastery_student_concept')
    )
    op.create_index(op.f('ix_mastery_records_school_id'), 'mastery_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_mastery_records_student_id'), 'mastery_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_mastery_records_subject_id'), 'mastery_records', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mastery_records_subject_id'), table_name='mastery_records')
    op.drop_index(op.f('ix_mastery_records_student_id'), table_name='mastery_records')
    op.drop_index(op.f('ix_mastery_records_school_id'), table_name='mastery_records')
    op.drop_table('mastery_records')
    # ### end Alembic commands ###
