"""D6: add review session summaries

Revision ID: 83bcb2215849
Revises: 6d9fe6080e14
Create Date: 2026-09-23 23:32:54.169566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bcb2215849'
down_revision: Union[str, Sequence[str], None] = '6d9fe6080e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_session_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_attempts >= 1', name='ck_review_summary_attempts'),
    sa.ForeignKeyConstraint(['lesson_id'], ['review_lessons.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_review_summary_session')
    )
    op.create_index(op.f('ix_review_session_summaries_school_id'), 'review_session_summaries', ['school_id'], unique=False)
    op.create_index(op.f('ix_review_session_summaries_student_id'), 'review_session_summaries', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_session_summaries_student_id'), table_name='review_session_summaries')
    op.drop_index(op.f('ix_review_session_summaries_school_id'), table_name='review_session_summaries')
    op.drop_table('review_session_summaries')
    # ### end Alembic commands ###
